### ISSUE TITLE
enable and disable plugins without restarting

### ISSUE THREAD

**Issue by boubouhkarim** [indico/flask-pluginengine#8]
Hi,
can we enable and disable plugins without restarting the flask server ?

i'm implementing a system where the user should be able to enable or disable plugins while the flask application is running.

**Comment by ThiefMaster** [comment]
No, and this is one of the things we will never support.

Plugins may provide blueprints, and you cannot register/unregister blueprints at runtime. Also, if you have multiple worker processes there'd be no way to synchronize such a change across them, so we'd need to check if a plugin is enabled during every single action involving plugins.

If you usecase requires it, the best option would be always loading plugins you may need, and then having a separate enabled/disabled option on the plugin level. This would then be stored e.g. in your database and you'd check it whenever necessary.

**Comment by boubouhkarim** [comment]
ah thank you,
i'll look to set something on plugin level to just prevent the access to plugin routes while the plugin is disabled.
